# Generated by Django 3.2.25 on 2025-02-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameBasics',
            fields=[
                ('nconst', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('primaryName', models.CharField(max_length=255)),
                ('birthYear', models.IntegerField(blank=True, null=True)),
                ('deathYear', models.IntegerField(blank=True, null=True)),
                ('primaryProfession', models.JSONField(default=list)),
                ('knownForTitles', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TitleBasics',
            fields=[
                ('tconst', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=255)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('originalTitle', models.CharField(max_length=255)),
                ('isAdult', models.BooleanField()),
                ('startYear', models.IntegerField(blank=True, null=True)),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('runtimeMinutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TitleCrew',
            fields=[
                ('tconst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='crew', serialize=False, to='miapp.titlebasics')),
                ('directors', models.JSONField(default=list)),
                ('writers', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TitleRatings',
            fields=[
                ('tconst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='miapp.titlebasics')),
                ('averageRating', models.FloatField()),
                ('numVotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleAkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleId', models.CharField(max_length=255)),
                ('ordering', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('types', models.JSONField()),
                ('attributes', models.JSONField()),
                ('isOriginalTitle', models.BooleanField()),
            ],
            options={
                'unique_together': {('titleId', 'ordering')},
            },
        ),
        migrations.CreateModel(
            name='TitlePrincipals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('characters', models.CharField(blank=True, max_length=255, null=True)),
                ('nconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='miapp.namebasics')),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='miapp.titlebasics')),
            ],
            options={
                'unique_together': {('tconst', 'ordering')},
            },
        ),
        migrations.CreateModel(
            name='TitleEpisode',
            fields=[
                ('tconst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='episode', serialize=False, to='miapp.titlebasics')),
                ('seasonNumber', models.IntegerField(blank=True, null=True)),
                ('episodeNumber', models.IntegerField(blank=True, null=True)),
                ('parentTconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='miapp.titlebasics')),
            ],
        ),
    ]
